#!/usr/bin/env bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$SCRIPTS_DIR/../"

env

declare -a binaries=("go" "yarn" "pip3")

for binary in "${binaries[@]}"
do
  if [ -z $(which $binary) ]
  then
    echo "${binary} needs to be installed"
    exit 1
  fi
done

cd $PROJECT_ROOT

rm -rf env/
rm -rf $HOME/.cache/vim 2> /dev/null
yarn install
go install golang.org/x/tools/gopls
pip3 install --upgrade --user virtualenv
virtualenv env --python=python3
env/bin/pip3 install --upgrade -r requirements.txt  --no-warn-script-location
