" Generated by vim-plug
" Sun 22 Aug 2021 12:26:42 AM EDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ack.vim'].commit = '36e40f9ec91bdbf6f1adf408522a73a6925c3042'
silent! let g:plugs['coc-tailwind-intellisense'].commit = '62846afd7991da59e62feaa5f092df24cf1fb461'
silent! let g:plugs['coc.nvim'].commit = '5f5e3135de04c9e245c1ecf53b67836c692fd06a'
silent! let g:plugs['emmet-vim'].commit = '46e60676f2d6b6f02478e444ae23ee804a3de45e'
silent! let g:plugs['fzf'].commit = '29851c18aa47ad4b4cbf92358cfbe11935f0c033'
silent! let g:plugs['fzf.vim'].commit = '02a192ea0bed22a015e005b281e55e0da2a8e496'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['indentLine'].commit = '5617a1cf7d315e6e6f84d825c85e3b669d220bfa'
silent! let g:plugs['neco-vim'].commit = '2b1dca6ca16d6f5655748fcd4d54d772fcfd0d81'
silent! let g:plugs['popup-menu.nvim'].commit = 'b618bd0c824a20417d845fa0022327228e6988a2'
silent! let g:plugs['scss-syntax.vim'].commit = 'bda22a93d1dcfcb8ee13be1988560d9bb5bd0fef'
silent! let g:plugs['spelunker.vim'].commit = 'a0bc530f62798bbe053905555a4aa9ed713485eb'
silent! let g:plugs['vim-airline'].commit = 'cb1bc19064d3762e4e08103afb37a246b797d902'
silent! let g:plugs['vim-airline-themes'].commit = 'd148d42d9caf331ff08b6cae683d5b210003cde7'
silent! let g:plugs['vim-better-whitespace'].commit = '8cf4b2175dd61416c2fe7d3234324a6c59d678de'
silent! let g:plugs['vim-buftabline'].commit = '73b9ef5dcb6cdf6488bc88adb382f20bc3e3262a'
silent! let g:plugs['vim-commentary'].commit = 'f8238d70f873969fb41bf6a6b07ca63a4c0b82b1'
silent! let g:plugs['vim-devicons'].commit = 'c17487d0dfafb204fb43c60dc58a4ea5c4728fe6'
silent! let g:plugs['vim-go'].commit = '755b498c7604e7aee4d001d2a78c2d1e079eb8d5'
silent! let g:plugs['vim-json'].commit = '3727f089410e23ae113be6222e8a08dd2613ecf2'
silent! let g:plugs['vim-toml'].commit = '3c5face8e8944a217af45bc5bb708ff7dfcf1a54'
silent! let g:plugs['vim-vinegar'].commit = '5f48edf4dcc130ae4a658541c0d6f72a558bc70d'
silent! let g:plugs['yats.vim'].commit = '11112853180a933574f431cf78cd5a462ee3f473'

PlugUpdate!

