" Generated by vim-plug
" Tue Jul 26 22:19:55 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ack.vim'].commit = '36e40f9ec91bdbf6f1adf408522a73a6925c3042'
silent! let g:plugs['coc.nvim'].commit = '43744ba82bd348ea971b87483a13f06f3e46c94b'
silent! let g:plugs['emmet-vim'].commit = 'def5d57a1ae5afb1b96ebe83c4652d1c03640f4d'
silent! let g:plugs['fzf'].commit = 'ecc418ba77e52660ffdd9ed84727b12c3f377680'
silent! let g:plugs['fzf.vim'].commit = 'c311c0a95fc2529c26ab36a8f530e9dd4426304c'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['indentLine'].commit = '7753505f3c500ec88d11e9373d05250f49c1d900'
silent! let g:plugs['neco-vim'].commit = 'facc3db7c5836fe2424936e8dd06f227e20f96db'
silent! let g:plugs['popup-menu.nvim'].commit = 'b618bd0c824a20417d845fa0022327228e6988a2'
silent! let g:plugs['scss-syntax.vim'].commit = 'bda22a93d1dcfcb8ee13be1988560d9bb5bd0fef'
silent! let g:plugs['spelunker.vim'].commit = 'a0bc530f62798bbe053905555a4aa9ed713485eb'
silent! let g:plugs['vim-airline'].commit = 'ebb89a0846ff8b8bc64579155d661b825f97d3f2'
silent! let g:plugs['vim-airline-themes'].commit = '55bad92d246a31e3425dfaf16b7eec657eab1fad'
silent! let g:plugs['vim-better-whitespace'].commit = '1b22dc57a2751c7afbc6025a7da39b7c22db635d'
silent! let g:plugs['vim-buftabline'].commit = '73b9ef5dcb6cdf6488bc88adb382f20bc3e3262a'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-devicons'].commit = 'a2258658661e42dd4cdba4958805dbad1fe29ef4'
silent! let g:plugs['vim-go'].commit = '7ec0a19a78a453686cb5c9776e506375562f9a1f'
silent! let g:plugs['vim-json'].commit = '3727f089410e23ae113be6222e8a08dd2613ecf2'
silent! let g:plugs['vim-toml'].commit = '89bcca8a3aeab360f6dfe5ce70999fc928669411'
silent! let g:plugs['vim-vinegar'].commit = 'bb1bcddf43cfebe05eb565a84ab069b357d0b3d6'
silent! let g:plugs['yats.vim'].commit = '68cd1da2bcea5fb3fbe6b6266958ae7c72e814da'

PlugUpdate!

